// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// egmifs_cpp
Rcpp::List egmifs_cpp(const arma::mat& X, const arma::vec& y, const arma::mat& w, const arma::vec& offset, const arma::vec& weight_vec, double enet_alpha, double epsilon_start, double epsilon_max, double epsilon_min, uint32_t null_iteration_max, uint32_t stagewise_iteration_max, double null_family_parameter_abs_tol, double stagewise_objective_rel_tol, double stagewise_beta_step_norm_tol, SEXP family, SEXP link_func, Rcpp::Nullable<Rcpp::List> criteria, double loglik_reltol_cutoff, double enet_abs_tol, double enet_rel_tol, uint32_t enet_max_iter, bool verbose, int state_track_strategy, uint64_t state_track_freq, bool include_data, const arma::vec& theta_initial, const arma::vec& theta_lower_bounds, const arma::vec& theta_upper_bounds, int nonpen_nlopt_algorithm, double nonpen_nlopt_xtol_rel, double nonpen_nlopt_ftol_rel, int nonpen_nlopt_maxeval, int family_nlopt_algorithm, double family_nlopt_xtol_rel, double family_nlopt_ftol_rel, int family_nlopt_maxeval, int link_nlopt_algorithm, double link_nlopt_xtol_rel, double link_nlopt_ftol_rel, int link_nlopt_maxeval, SEXP family_link);
RcppExport SEXP _egmifs_egmifs_cpp(SEXP XSEXP, SEXP ySEXP, SEXP wSEXP, SEXP offsetSEXP, SEXP weight_vecSEXP, SEXP enet_alphaSEXP, SEXP epsilon_startSEXP, SEXP epsilon_maxSEXP, SEXP epsilon_minSEXP, SEXP null_iteration_maxSEXP, SEXP stagewise_iteration_maxSEXP, SEXP null_family_parameter_abs_tolSEXP, SEXP stagewise_objective_rel_tolSEXP, SEXP stagewise_beta_step_norm_tolSEXP, SEXP familySEXP, SEXP link_funcSEXP, SEXP criteriaSEXP, SEXP loglik_reltol_cutoffSEXP, SEXP enet_abs_tolSEXP, SEXP enet_rel_tolSEXP, SEXP enet_max_iterSEXP, SEXP verboseSEXP, SEXP state_track_strategySEXP, SEXP state_track_freqSEXP, SEXP include_dataSEXP, SEXP theta_initialSEXP, SEXP theta_lower_boundsSEXP, SEXP theta_upper_boundsSEXP, SEXP nonpen_nlopt_algorithmSEXP, SEXP nonpen_nlopt_xtol_relSEXP, SEXP nonpen_nlopt_ftol_relSEXP, SEXP nonpen_nlopt_maxevalSEXP, SEXP family_nlopt_algorithmSEXP, SEXP family_nlopt_xtol_relSEXP, SEXP family_nlopt_ftol_relSEXP, SEXP family_nlopt_maxevalSEXP, SEXP link_nlopt_algorithmSEXP, SEXP link_nlopt_xtol_relSEXP, SEXP link_nlopt_ftol_relSEXP, SEXP link_nlopt_maxevalSEXP, SEXP family_linkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weight_vec(weight_vecSEXP);
    Rcpp::traits::input_parameter< double >::type enet_alpha(enet_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon_start(epsilon_startSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon_max(epsilon_maxSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon_min(epsilon_minSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type null_iteration_max(null_iteration_maxSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type stagewise_iteration_max(stagewise_iteration_maxSEXP);
    Rcpp::traits::input_parameter< double >::type null_family_parameter_abs_tol(null_family_parameter_abs_tolSEXP);
    Rcpp::traits::input_parameter< double >::type stagewise_objective_rel_tol(stagewise_objective_rel_tolSEXP);
    Rcpp::traits::input_parameter< double >::type stagewise_beta_step_norm_tol(stagewise_beta_step_norm_tolSEXP);
    Rcpp::traits::input_parameter< SEXP >::type family(familySEXP);
    Rcpp::traits::input_parameter< SEXP >::type link_func(link_funcSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type criteria(criteriaSEXP);
    Rcpp::traits::input_parameter< double >::type loglik_reltol_cutoff(loglik_reltol_cutoffSEXP);
    Rcpp::traits::input_parameter< double >::type enet_abs_tol(enet_abs_tolSEXP);
    Rcpp::traits::input_parameter< double >::type enet_rel_tol(enet_rel_tolSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type enet_max_iter(enet_max_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type state_track_strategy(state_track_strategySEXP);
    Rcpp::traits::input_parameter< uint64_t >::type state_track_freq(state_track_freqSEXP);
    Rcpp::traits::input_parameter< bool >::type include_data(include_dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_initial(theta_initialSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_lower_bounds(theta_lower_boundsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_upper_bounds(theta_upper_boundsSEXP);
    Rcpp::traits::input_parameter< int >::type nonpen_nlopt_algorithm(nonpen_nlopt_algorithmSEXP);
    Rcpp::traits::input_parameter< double >::type nonpen_nlopt_xtol_rel(nonpen_nlopt_xtol_relSEXP);
    Rcpp::traits::input_parameter< double >::type nonpen_nlopt_ftol_rel(nonpen_nlopt_ftol_relSEXP);
    Rcpp::traits::input_parameter< int >::type nonpen_nlopt_maxeval(nonpen_nlopt_maxevalSEXP);
    Rcpp::traits::input_parameter< int >::type family_nlopt_algorithm(family_nlopt_algorithmSEXP);
    Rcpp::traits::input_parameter< double >::type family_nlopt_xtol_rel(family_nlopt_xtol_relSEXP);
    Rcpp::traits::input_parameter< double >::type family_nlopt_ftol_rel(family_nlopt_ftol_relSEXP);
    Rcpp::traits::input_parameter< int >::type family_nlopt_maxeval(family_nlopt_maxevalSEXP);
    Rcpp::traits::input_parameter< int >::type link_nlopt_algorithm(link_nlopt_algorithmSEXP);
    Rcpp::traits::input_parameter< double >::type link_nlopt_xtol_rel(link_nlopt_xtol_relSEXP);
    Rcpp::traits::input_parameter< double >::type link_nlopt_ftol_rel(link_nlopt_ftol_relSEXP);
    Rcpp::traits::input_parameter< int >::type link_nlopt_maxeval(link_nlopt_maxevalSEXP);
    Rcpp::traits::input_parameter< SEXP >::type family_link(family_linkSEXP);
    rcpp_result_gen = Rcpp::wrap(egmifs_cpp(X, y, w, offset, weight_vec, enet_alpha, epsilon_start, epsilon_max, epsilon_min, null_iteration_max, stagewise_iteration_max, null_family_parameter_abs_tol, stagewise_objective_rel_tol, stagewise_beta_step_norm_tol, family, link_func, criteria, loglik_reltol_cutoff, enet_abs_tol, enet_rel_tol, enet_max_iter, verbose, state_track_strategy, state_track_freq, include_data, theta_initial, theta_lower_bounds, theta_upper_bounds, nonpen_nlopt_algorithm, nonpen_nlopt_xtol_rel, nonpen_nlopt_ftol_rel, nonpen_nlopt_maxeval, family_nlopt_algorithm, family_nlopt_xtol_rel, family_nlopt_ftol_rel, family_nlopt_maxeval, link_nlopt_algorithm, link_nlopt_xtol_rel, link_nlopt_ftol_rel, link_nlopt_maxeval, family_link));
    return rcpp_result_gen;
END_RCPP
}
// example_create_log_link
SEXP example_create_log_link();
RcppExport SEXP _egmifs_example_create_log_link() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(example_create_log_link());
    return rcpp_result_gen;
END_RCPP
}
// example_create_softplus_link
SEXP example_create_softplus_link();
RcppExport SEXP _egmifs_example_create_softplus_link() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(example_create_softplus_link());
    return rcpp_result_gen;
END_RCPP
}
// example_create_poisson_family
SEXP example_create_poisson_family(const double mu_min_cap, const double mu_max_cap);
RcppExport SEXP _egmifs_example_create_poisson_family(SEXP mu_min_capSEXP, SEXP mu_max_capSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type mu_min_cap(mu_min_capSEXP);
    Rcpp::traits::input_parameter< const double >::type mu_max_cap(mu_max_capSEXP);
    rcpp_result_gen = Rcpp::wrap(example_create_poisson_family(mu_min_cap, mu_max_cap));
    return rcpp_result_gen;
END_RCPP
}
// example_create_nb2_family
SEXP example_create_nb2_family(const double mu_min_cap, const double mu_max_cap, const double poisson_fallback_eps, const double dispersion_initial, const double dispersion_lower_bound, const double dispersion_upper_bound);
RcppExport SEXP _egmifs_example_create_nb2_family(SEXP mu_min_capSEXP, SEXP mu_max_capSEXP, SEXP poisson_fallback_epsSEXP, SEXP dispersion_initialSEXP, SEXP dispersion_lower_boundSEXP, SEXP dispersion_upper_boundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type mu_min_cap(mu_min_capSEXP);
    Rcpp::traits::input_parameter< const double >::type mu_max_cap(mu_max_capSEXP);
    Rcpp::traits::input_parameter< const double >::type poisson_fallback_eps(poisson_fallback_epsSEXP);
    Rcpp::traits::input_parameter< const double >::type dispersion_initial(dispersion_initialSEXP);
    Rcpp::traits::input_parameter< const double >::type dispersion_lower_bound(dispersion_lower_boundSEXP);
    Rcpp::traits::input_parameter< const double >::type dispersion_upper_bound(dispersion_upper_boundSEXP);
    rcpp_result_gen = Rcpp::wrap(example_create_nb2_family(mu_min_cap, mu_max_cap, poisson_fallback_eps, dispersion_initial, dispersion_lower_bound, dispersion_upper_bound));
    return rcpp_result_gen;
END_RCPP
}
// example_create_nb2_log_family_link
SEXP example_create_nb2_log_family_link(const double mu_min_cap, const double mu_max_cap, const double poisson_fallback_eps, const double dispersion_initial, const double dispersion_lower_bound, const double dispersion_upper_bound);
RcppExport SEXP _egmifs_example_create_nb2_log_family_link(SEXP mu_min_capSEXP, SEXP mu_max_capSEXP, SEXP poisson_fallback_epsSEXP, SEXP dispersion_initialSEXP, SEXP dispersion_lower_boundSEXP, SEXP dispersion_upper_boundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type mu_min_cap(mu_min_capSEXP);
    Rcpp::traits::input_parameter< const double >::type mu_max_cap(mu_max_capSEXP);
    Rcpp::traits::input_parameter< const double >::type poisson_fallback_eps(poisson_fallback_epsSEXP);
    Rcpp::traits::input_parameter< const double >::type dispersion_initial(dispersion_initialSEXP);
    Rcpp::traits::input_parameter< const double >::type dispersion_lower_bound(dispersion_lower_boundSEXP);
    Rcpp::traits::input_parameter< const double >::type dispersion_upper_bound(dispersion_upper_boundSEXP);
    rcpp_result_gen = Rcpp::wrap(example_create_nb2_log_family_link(mu_min_cap, mu_max_cap, poisson_fallback_eps, dispersion_initial, dispersion_lower_bound, dispersion_upper_bound));
    return rcpp_result_gen;
END_RCPP
}
// example_create_aic_criterion
SEXP example_create_aic_criterion();
RcppExport SEXP _egmifs_example_create_aic_criterion() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(example_create_aic_criterion());
    return rcpp_result_gen;
END_RCPP
}
// example_create_bic_criterion
SEXP example_create_bic_criterion();
RcppExport SEXP _egmifs_example_create_bic_criterion() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(example_create_bic_criterion());
    return rcpp_result_gen;
END_RCPP
}
// example_create_information_criterion
SEXP example_create_information_criterion(const std::string& name, const int penalty_type, const int df_type, const double gamma);
RcppExport SEXP _egmifs_example_create_information_criterion(SEXP nameSEXP, SEXP penalty_typeSEXP, SEXP df_typeSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type name(nameSEXP);
    Rcpp::traits::input_parameter< const int >::type penalty_type(penalty_typeSEXP);
    Rcpp::traits::input_parameter< const int >::type df_type(df_typeSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(example_create_information_criterion(name, penalty_type, df_type, gamma));
    return rcpp_result_gen;
END_RCPP
}
// create_r_link
SEXP create_r_link(const std::string& name, Rcpp::Function prepare, Rcpp::Function inverse, Rcpp::Function grad, arma::vec initial_parameters, arma::vec lower_bounds, arma::vec upper_bounds, Rcpp::Environment environment);
RcppExport SEXP _egmifs_create_r_link(SEXP nameSEXP, SEXP prepareSEXP, SEXP inverseSEXP, SEXP gradSEXP, SEXP initial_parametersSEXP, SEXP lower_boundsSEXP, SEXP upper_boundsSEXP, SEXP environmentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type name(nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type prepare(prepareSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type inverse(inverseSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type grad(gradSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type initial_parameters(initial_parametersSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lower_bounds(lower_boundsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type upper_bounds(upper_boundsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Environment >::type environment(environmentSEXP);
    rcpp_result_gen = Rcpp::wrap(create_r_link(name, prepare, inverse, grad, initial_parameters, lower_bounds, upper_bounds, environment));
    return rcpp_result_gen;
END_RCPP
}
// create_r_family
SEXP create_r_family(const std::string& name, Rcpp::Function prepare, Rcpp::Function negloglik, Rcpp::Function grad, arma::vec initial_parameters, arma::vec lower_bounds, arma::vec upper_bounds, Rcpp::Environment environment);
RcppExport SEXP _egmifs_create_r_family(SEXP nameSEXP, SEXP prepareSEXP, SEXP negloglikSEXP, SEXP gradSEXP, SEXP initial_parametersSEXP, SEXP lower_boundsSEXP, SEXP upper_boundsSEXP, SEXP environmentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type name(nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type prepare(prepareSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type negloglik(negloglikSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type grad(gradSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type initial_parameters(initial_parametersSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lower_bounds(lower_boundsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type upper_bounds(upper_boundsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Environment >::type environment(environmentSEXP);
    rcpp_result_gen = Rcpp::wrap(create_r_family(name, prepare, negloglik, grad, initial_parameters, lower_bounds, upper_bounds, environment));
    return rcpp_result_gen;
END_RCPP
}
// create_r_family_link
SEXP create_r_family_link(const std::string& family_name, const std::string& link_name, Rcpp::Function prepare, Rcpp::Function inverse, Rcpp::Function negloglik, Rcpp::Function grad, arma::vec family_initial_parameters, arma::vec family_lower_bounds, arma::vec family_upper_bounds, arma::vec link_initial_parameters, arma::vec link_lower_bounds, arma::vec link_upper_bounds, Rcpp::Environment environment);
RcppExport SEXP _egmifs_create_r_family_link(SEXP family_nameSEXP, SEXP link_nameSEXP, SEXP prepareSEXP, SEXP inverseSEXP, SEXP negloglikSEXP, SEXP gradSEXP, SEXP family_initial_parametersSEXP, SEXP family_lower_boundsSEXP, SEXP family_upper_boundsSEXP, SEXP link_initial_parametersSEXP, SEXP link_lower_boundsSEXP, SEXP link_upper_boundsSEXP, SEXP environmentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type family_name(family_nameSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link_name(link_nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type prepare(prepareSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type inverse(inverseSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type negloglik(negloglikSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type grad(gradSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type family_initial_parameters(family_initial_parametersSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type family_lower_bounds(family_lower_boundsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type family_upper_bounds(family_upper_boundsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type link_initial_parameters(link_initial_parametersSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type link_lower_bounds(link_lower_boundsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type link_upper_bounds(link_upper_boundsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Environment >::type environment(environmentSEXP);
    rcpp_result_gen = Rcpp::wrap(create_r_family_link(family_name, link_name, prepare, inverse, negloglik, grad, family_initial_parameters, family_lower_bounds, family_upper_bounds, link_initial_parameters, link_lower_bounds, link_upper_bounds, environment));
    return rcpp_result_gen;
END_RCPP
}
// create_r_criterion
SEXP create_r_criterion(const std::string& name, Rcpp::Function prepare, Rcpp::Function evaluate, Rcpp::Environment environment);
RcppExport SEXP _egmifs_create_r_criterion(SEXP nameSEXP, SEXP prepareSEXP, SEXP evaluateSEXP, SEXP environmentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type name(nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type prepare(prepareSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type evaluate(evaluateSEXP);
    Rcpp::traits::input_parameter< Rcpp::Environment >::type environment(environmentSEXP);
    rcpp_result_gen = Rcpp::wrap(create_r_criterion(name, prepare, evaluate, environment));
    return rcpp_result_gen;
END_RCPP
}
// inspect_link_plugin
Rcpp::List inspect_link_plugin(SEXP pointer);
RcppExport SEXP _egmifs_inspect_link_plugin(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(inspect_link_plugin(pointer));
    return rcpp_result_gen;
END_RCPP
}
// inspect_family_plugin
Rcpp::List inspect_family_plugin(SEXP pointer);
RcppExport SEXP _egmifs_inspect_family_plugin(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(inspect_family_plugin(pointer));
    return rcpp_result_gen;
END_RCPP
}
// inspect_family_link_plugin
Rcpp::List inspect_family_link_plugin(SEXP pointer);
RcppExport SEXP _egmifs_inspect_family_link_plugin(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(inspect_family_link_plugin(pointer));
    return rcpp_result_gen;
END_RCPP
}
// inspect_criterion_plugin
Rcpp::List inspect_criterion_plugin(SEXP pointer);
RcppExport SEXP _egmifs_inspect_criterion_plugin(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(inspect_criterion_plugin(pointer));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_egmifs_egmifs_cpp", (DL_FUNC) &_egmifs_egmifs_cpp, 41},
    {"_egmifs_example_create_log_link", (DL_FUNC) &_egmifs_example_create_log_link, 0},
    {"_egmifs_example_create_softplus_link", (DL_FUNC) &_egmifs_example_create_softplus_link, 0},
    {"_egmifs_example_create_poisson_family", (DL_FUNC) &_egmifs_example_create_poisson_family, 2},
    {"_egmifs_example_create_nb2_family", (DL_FUNC) &_egmifs_example_create_nb2_family, 6},
    {"_egmifs_example_create_nb2_log_family_link", (DL_FUNC) &_egmifs_example_create_nb2_log_family_link, 6},
    {"_egmifs_example_create_aic_criterion", (DL_FUNC) &_egmifs_example_create_aic_criterion, 0},
    {"_egmifs_example_create_bic_criterion", (DL_FUNC) &_egmifs_example_create_bic_criterion, 0},
    {"_egmifs_example_create_information_criterion", (DL_FUNC) &_egmifs_example_create_information_criterion, 4},
    {"_egmifs_create_r_link", (DL_FUNC) &_egmifs_create_r_link, 8},
    {"_egmifs_create_r_family", (DL_FUNC) &_egmifs_create_r_family, 8},
    {"_egmifs_create_r_family_link", (DL_FUNC) &_egmifs_create_r_family_link, 13},
    {"_egmifs_create_r_criterion", (DL_FUNC) &_egmifs_create_r_criterion, 4},
    {"_egmifs_inspect_link_plugin", (DL_FUNC) &_egmifs_inspect_link_plugin, 1},
    {"_egmifs_inspect_family_plugin", (DL_FUNC) &_egmifs_inspect_family_plugin, 1},
    {"_egmifs_inspect_family_link_plugin", (DL_FUNC) &_egmifs_inspect_family_link_plugin, 1},
    {"_egmifs_inspect_criterion_plugin", (DL_FUNC) &_egmifs_inspect_criterion_plugin, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_egmifs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
