# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

egmifs_cpp <- function(X, y, w, offset, weight_vec, enet_alpha, epsilon_start, epsilon_max, epsilon_min, null_iteration_max, stagewise_iteration_max, null_family_parameter_abs_tol, stagewise_objective_rel_tol, stagewise_beta_step_norm_tol, family, link_func, criteria, loglik_reltol_cutoff, enet_abs_tol, enet_rel_tol, enet_max_iter, verbose, state_track_strategy, state_track_freq, include_data, theta_initial, theta_lower_bounds, theta_upper_bounds, nonpen_nlopt_algorithm, nonpen_nlopt_xtol_rel, nonpen_nlopt_ftol_rel, nonpen_nlopt_maxeval, family_nlopt_algorithm, family_nlopt_xtol_rel, family_nlopt_ftol_rel, family_nlopt_maxeval, link_nlopt_algorithm, link_nlopt_xtol_rel, link_nlopt_ftol_rel, link_nlopt_maxeval, family_link = NULL) {
    .Call(`_egmifs_egmifs_cpp`, X, y, w, offset, weight_vec, enet_alpha, epsilon_start, epsilon_max, epsilon_min, null_iteration_max, stagewise_iteration_max, null_family_parameter_abs_tol, stagewise_objective_rel_tol, stagewise_beta_step_norm_tol, family, link_func, criteria, loglik_reltol_cutoff, enet_abs_tol, enet_rel_tol, enet_max_iter, verbose, state_track_strategy, state_track_freq, include_data, theta_initial, theta_lower_bounds, theta_upper_bounds, nonpen_nlopt_algorithm, nonpen_nlopt_xtol_rel, nonpen_nlopt_ftol_rel, nonpen_nlopt_maxeval, family_nlopt_algorithm, family_nlopt_xtol_rel, family_nlopt_ftol_rel, family_nlopt_maxeval, link_nlopt_algorithm, link_nlopt_xtol_rel, link_nlopt_ftol_rel, link_nlopt_maxeval, family_link)
}

example_create_log_link <- function() {
    .Call(`_egmifs_example_create_log_link`)
}

example_create_softplus_link <- function() {
    .Call(`_egmifs_example_create_softplus_link`)
}

example_create_poisson_family <- function(mu_min_cap = 1e-12, mu_max_cap = 1e12) {
    .Call(`_egmifs_example_create_poisson_family`, mu_min_cap, mu_max_cap)
}

example_create_nb2_family <- function(mu_min_cap = 1e-12, mu_max_cap = 1e12, poisson_fallback_eps = 1e-8, dispersion_initial = 1e-4, dispersion_lower_bound = 1e-12, dispersion_upper_bound = 1e12) {
    .Call(`_egmifs_example_create_nb2_family`, mu_min_cap, mu_max_cap, poisson_fallback_eps, dispersion_initial, dispersion_lower_bound, dispersion_upper_bound)
}

example_create_nb2_log_family_link <- function(mu_min_cap = 1e-12, mu_max_cap = 1e12, poisson_fallback_eps = 1e-8, dispersion_initial = 1e-4, dispersion_lower_bound = 1e-12, dispersion_upper_bound = 1e12) {
    .Call(`_egmifs_example_create_nb2_log_family_link`, mu_min_cap, mu_max_cap, poisson_fallback_eps, dispersion_initial, dispersion_lower_bound, dispersion_upper_bound)
}

example_create_aic_criterion <- function() {
    .Call(`_egmifs_example_create_aic_criterion`)
}

example_create_bic_criterion <- function() {
    .Call(`_egmifs_example_create_bic_criterion`)
}

example_create_information_criterion <- function(name, penalty_type, df_type, gamma = 0.5) {
    .Call(`_egmifs_example_create_information_criterion`, name, penalty_type, df_type, gamma)
}

create_r_link <- function(name, prepare, inverse, grad, initial_parameters, lower_bounds, upper_bounds, environment) {
    .Call(`_egmifs_create_r_link`, name, prepare, inverse, grad, initial_parameters, lower_bounds, upper_bounds, environment)
}

create_r_family <- function(name, prepare, negloglik, grad, initial_parameters, lower_bounds, upper_bounds, environment) {
    .Call(`_egmifs_create_r_family`, name, prepare, negloglik, grad, initial_parameters, lower_bounds, upper_bounds, environment)
}

create_r_family_link <- function(family_name, link_name, prepare, inverse, negloglik, grad, family_initial_parameters, family_lower_bounds, family_upper_bounds, link_initial_parameters, link_lower_bounds, link_upper_bounds, environment) {
    .Call(`_egmifs_create_r_family_link`, family_name, link_name, prepare, inverse, negloglik, grad, family_initial_parameters, family_lower_bounds, family_upper_bounds, link_initial_parameters, link_lower_bounds, link_upper_bounds, environment)
}

create_r_criterion <- function(name, prepare, evaluate, environment) {
    .Call(`_egmifs_create_r_criterion`, name, prepare, evaluate, environment)
}

inspect_link_plugin <- function(pointer) {
    .Call(`_egmifs_inspect_link_plugin`, pointer)
}

inspect_family_plugin <- function(pointer) {
    .Call(`_egmifs_inspect_family_plugin`, pointer)
}

inspect_family_link_plugin <- function(pointer) {
    .Call(`_egmifs_inspect_family_link_plugin`, pointer)
}

inspect_criterion_plugin <- function(pointer) {
    .Call(`_egmifs_inspect_criterion_plugin`, pointer)
}

